/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cprassoc.solr.auth.ui;

import com.cprassoc.solr.auth.SolrAuthActionController;
import com.cprassoc.solr.auth.SolrAuthManager;
import java.io.File;
import java.util.Properties;
import javax.swing.JFileChooser;

/**
 *
 * @author kevin
 */
public class SolrSecurityPropertyManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form SolrSecurityPropertyManager
     */
    Properties loadedProperties = null;

    public SolrSecurityPropertyManagerFrame() {
        initComponents();
        init();
    }

    public SolrSecurityPropertyManagerFrame(Properties p) {
        this.loadedProperties = p;
        initComponents();
        init();
    }

    private void init() {
        this.setSize(700, 400);
        if (this.loadedProperties != null) {
            this.solrInstallDirPath.setText(loadedProperties.getProperty(SolrAuthPropertyKey.solrInstallPath.getKey()));
            this.solrHostPort.setText(loadedProperties.getProperty(SolrAuthPropertyKey.solrHostPort.getKey()));
            this.collectionField.setText(loadedProperties.getProperty(SolrAuthPropertyKey.defaultCollection.getKey()));
            this.zooKeeperPort.setText(loadedProperties.getProperty(SolrAuthPropertyKey.zookeeperPort.getKey()));
            if (loadedProperties.getProperty(SolrAuthPropertyKey.isUsingSSL.getKey()) != null
                    && loadedProperties.getProperty(SolrAuthPropertyKey.isUsingSSL.getKey()).equalsIgnoreCase("true")) {
                this.usingSSL.setSelected(true);
            } else {
                this.usingSSL.setSelected(false);
            }
            this.solrAdminUserField.setText(loadedProperties.getProperty(SolrAuthPropertyKey.solrAdminUser.getKey()));
            this.solrUserPwdField.setText(loadedProperties.getProperty(SolrAuthPropertyKey.solrAdminPwd.getKey()));
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolrAuthMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolrAuthMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolrAuthMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolrAuthMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolrSecurityPropertyManagerFrame().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        solrInstallDirPath = new javax.swing.JTextField();
        solrHostPort = new javax.swing.JTextField();
        zooKeeperPort = new javax.swing.JTextField();
        usingSSL = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        collectionField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        solrAdminUserField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        solrUserPwdField = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property Manager");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Path to Solr Install:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Solr Host:Port");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ZooKeeper Host/Port: ");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doSaveAction(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCancelAction(evt);
            }
        });

        solrInstallDirPath.setText("/usr/share/solr");

        solrHostPort.setText("localhost:8983");

        zooKeeperPort.setText("localhost:9993");

        usingSSL.setBackground(new java.awt.Color(0, 51, 102));
        usingSSL.setForeground(new java.awt.Color(255, 255, 255));
        usingSSL.setText("Using SSL?");

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBrowseForSolrInstallDir(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Default Collection:");

        collectionField.setText("NAME-OF-YOUR-DEFAULT-COLLECTION");

        jButton2.setText("Load From File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doLoadFromFile(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Solr Admin User:");

        solrAdminUserField.setText("solr");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Solr Admin Password::");

        solrUserPwdField.setText("SolrRocks");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usingSSL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(58, 58, 58)
                                            .addComponent(solrHostPort, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(solrInstallDirPath, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(collectionField, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                                .addComponent(zooKeeperPort, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                                .addComponent(solrAdminUserField)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(solrUserPwdField)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(solrInstallDirPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(solrHostPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(zooKeeperPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(collectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(solrAdminUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(solrUserPwdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(cancelButton))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(usingSSL)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doSaveAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doSaveAction
        System.out.println("Saving...");
        Properties props = SolrAuthManager.getProperties();
        props.setProperty(SolrAuthPropertyKey.solrInstallPath.getKey(), this.solrInstallDirPath.getText());
        props.setProperty(SolrAuthPropertyKey.solrHostPort.getKey(), this.solrHostPort.getText());
        props.setProperty(SolrAuthPropertyKey.zookeeperPort.getKey(), this.zooKeeperPort.getText());
        props.setProperty(SolrAuthPropertyKey.defaultCollection.getKey(), this.collectionField.getText());
        props.setProperty(SolrAuthPropertyKey.solrAdminUser.getKey(), this.solrAdminUserField.getText());
        props.setProperty(SolrAuthPropertyKey.solrAdminPwd.getKey(), new String(this.solrUserPwdField.getPassword()));
        String sslEnabled = "false";
        if (this.usingSSL.isSelected()) {
            sslEnabled = "true";
        }
        props.setProperty(SolrAuthPropertyKey.isUsingSSL.getKey(), sslEnabled);
        SolrAuthActionController.doSavePropertiesAction(props);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_doSaveAction

    private void doCancelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCancelAction
        System.out.println("Cancel...");
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_doCancelAction

    private void doBrowseForSolrInstallDir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doBrowseForSolrInstallDir
        //Create a file chooser
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(SolrSecurityPropertyManagerFrame.this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            System.out.println("Opening: " + file.getName() + ".");
            this.solrInstallDirPath.setText(file.getAbsolutePath());
        } else {
            System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_doBrowseForSolrInstallDir

    private void doLoadFromFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doLoadFromFile
        // TODO add your handling code here:
    }//GEN-LAST:event_doLoadFromFile


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField collectionField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField solrAdminUserField;
    private javax.swing.JTextField solrHostPort;
    private javax.swing.JTextField solrInstallDirPath;
    private javax.swing.JPasswordField solrUserPwdField;
    private javax.swing.JCheckBox usingSSL;
    private javax.swing.JTextField zooKeeperPort;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cancelButton
     */
    public javax.swing.JButton getCancelButton() {
        return cancelButton;
    }

    /**
     * @return the saveButton
     */
    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    public enum SolrAuthPropertyKey {
        solrHostPort("solr.host.port"),
        solrInstallPath("solr.install.path"),
        isUsingSSL("solr.ssl.enabled"),
        zookeeperPort("solr.zookeeper.port"),
        defaultCollection("solr.default.collection"),
        solrAdminUser("solr.admin.user"),
        solrAdminPwd("solr.admin.pwd");
        private String key = "";

        private SolrAuthPropertyKey(String key) {
            this.key = key;
        }

        public String getKey() {
            return key;
        }
    }

    public static Properties getSolrAuthProperties() {
        Properties props = new Properties();
        SolrAuthPropertyKey p;
        for (int i = 0; i < SolrAuthPropertyKey.values().length; i++) {
            props.setProperty(SolrAuthPropertyKey.values()[i].getKey(), "");
        }
        return props;
    }

    public void loadSolrAuthProperties(Properties props) {

        SolrAuthPropertyKey p;
        for (int i = 0; i < SolrAuthPropertyKey.values().length; i++) {
            props.setProperty(SolrAuthPropertyKey.values()[i].getKey(), "");
        }

    }
}
